image: $REPO_URL/stage

services:
  - $REPO_URL/public/docker/library/docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - stage
  - prod

default:
  before_script:
    - sleep 3

deploy-stage:
  stage: stage
  tags:
    - kube-small-new
  script:
    - echo 'WORKING DEPLOY STAGE'
