image: $REPO_URL/stage

services:
  - $REPO_URL/public/docker/library/docker:dind

stages:
  - build
  # - test
  # - e2e
  # - release
  # - deployment

variables:
  BASE_IMAGE_NAME: ppdns-extensions
  DOCKER_HOST: tcp://localhost:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

default:
  before_script:
    - pip install $END_TO_END_LIB@$CI_COMMIT_REF_NAME || pip install $END_TO_END_LIB
    - e2e init

###############################################################
# Build Stage (jobs inside a stage run in parallel)
###############################################################

.BUILD:
  stage: build
  tags:
    - kube-new
  script:
    # try to download the multi-stage dependant image and retag it as latest
    - e2e dependencies docker/Dockerfile
    - docker buildx build
      -f docker/Dockerfile
      -t $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_SHA
      -t $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_REF_SLUG
      --cache-from=$REPO_URL/$BASE_IMAGE_NAME:latest
      .
    - docker push $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_REF_SLUG
    - docker run
      -e POLYSWARM_API_URL -e BATCH_SIZE -e APPLICATION=build
      -v $PWD/dist:/usr/src/app/dist:rw
      $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_REF_SLUG

  artifacts:
    name: "extensions-$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
    - "dist/*.zip"
    expire_in: 1 week


build-local:
  extends: .BUILD
  variables:
    POLYSWARM_API_URL: http://artifact-index-e2e:9696
    BATCH_SIZE: 3
    NODE_ENV: development


build-stage:
  extends: .BUILD
  variables:
    POLYSWARM_API_URL: https://api.stage-v3.polyswarm.network
    BATCH_SIZE: 10
    NODE_ENV: production


build-prod:
  extends: .BUILD
  variables:
    POLYSWARM_API_URL: https://api.polyswarm.network
    BATCH_SIZE: 10
    NODE_ENV: production
