name: NodeJS with Webpack

env:
  AI_BASE_URL: http://artifact-index-e2e:9696 # TODO: set this to prod/stage/etc

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: tag_name

      - name: Build
        run: |
          npm install
          npm run build
          xcrun safari-web-extension-converter ./build --project-location $PWD/safari --app-name ppdns --bundle-identifier ppdns --macos-only --copy-resources
          zip -r ppdns-safari-extension-${{ steps.tag_name.outputs.tag }}.zip ./safari

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_name.outputs.tag }}
          files: ppdns-*.zip
