name: NodeJS with Webpack

env:
  AI_BASE_URL: http://artifact-index-e2e:9696 # TODO: set this to prod/stage/etc

on:
  push:
    branches: [master, feature/DN5330-build]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ppdns-*.zip
