name: NodeJS with Webpack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, feature/DN5330-build]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v3
        with:
          ref: feature/DN5330-build

      - name: Build
        run: |
          npm install
          npm run build

      - uses: actions/checkout@v3
      - name: Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Pushing Build"
          git push
