name: NodeJS with Webpack

env:
  AI_BASE_URL: https://api.polyswarm.network
  BATCH_SIZE: 10
on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: tag_name

      - name: Build
        run: |
          npm install
          npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_name.outputs.tag }}
          files: ppdns-*.zip
